CREATE TABLE LANGUAGE(
	Language_ID INT AUTO_INCREMENT,
    Language_Code VARCHAR(10) NOT NULL,
    Created_Date DATETIME NOT NULL DEFAULT NOW(),
    Modified_Date DATETIME NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_LANGUAGE PRIMARY KEY (LANGUAGE_ID),
    CONSTRAINT UX_LANGUAGE_Code UNIQUE (Language_Code)
);

CREATE TABLE COLLECTIONS (
	Collection_ID INT AUTO_INCREMENT,
    Collection_Name VARCHAR(150) NOT NULL,
    Created_Date DATETIME NOT NULL DEFAULT NOW(),
    Modified_Date DATETIME NOT NULL DEFAULT NOW(),
    Constraint PK_COLLECTIONS PRIMARY KEY (Collection_ID)
);

CREATE TABLE GENRE(
	Genre_ID INT AUTO_INCREMENT,
    Genre_Name VARCHAR(100) NOT NULL,
    Created_Date DATETIME NOT NULL DEFAULT NOW(),
    Modified_Date DATETIME NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_GENRE PRIMARY KEY (Genre_ID)
);

CREATE TABLE MOVIE (
	Movie_ID int auto_increment,
    Original_Title varchar(200) NOT NULL,
    Display_Title varchar(200) not null,
    Language_ID INT NOT NULL,
    Collection_ID INT,
    Overview TEXT,
	Tagline VARCHAR(255),
	Release_Date DATE,
	Runtime_Min INT,
	Popularity DECIMAL(10,2),
	Vote_Count INT,
	Vote_Avg DECIMAL(4,2),
	Budget BIGINT,
	Revenue BIGINT,
	Adult_Flag TINYINT(1)      NOT NULL DEFAULT 0,
	Poster_Path VARCHAR(500),
	Backdrop_Path VARCHAR(500),
	Created_Date DATETIME NOT NULL DEFAULT NOW(),
	Modified_Date DATETIME NOT NULL DEFAULT NOW(),
	CONSTRAINT PK_MOVIE PRIMARY KEY (Movie_ID)
);

CREATE TABLE MOVIE_GENRE (
	Movie_Genre_ID INT AUTO_INCREMENT,
	Movie_ID INT NOT NULL,
	Genre_ID INT NOT NULL,
	Created_Date DATETIME NOT NULL DEFAULT NOW(),
	Modified_Date DATETIME  NOT NULL DEFAULT NOW(),
	CONSTRAINT PK_MOVIE_GENRE PRIMARY KEY (Movie_Genre_ID),
	CONSTRAINT UX_MOVIE_GENRE UNIQUE (Movie_ID, Genre_ID)
);

ALTER TABLE MOVIE
ADD CONSTRAINT FK_MOVIE_LANGUAGE_ID FOREIGN KEY (Language_ID)
REFERENCES LANGUAGE (Language_ID);

ALTER TABLE MOVIE
ADD CONSTRAINT FK_MOVIE_COLLECTION_ID FOREIGN KEY (Collection_ID)
REFERENCES COLLECTIONS (Collection_ID);

ALTER TABLE MOVIE_GENRE
ADD CONSTRAINT FK_MOVIE_GENRE_MOVIE_ID FOREIGN KEY (Movie_ID)
REFERENCES MOVIE (Movie_ID);

ALTER TABLE MOVIE_GENRE
ADD CONSTRAINT FK_MOVIE_GENRE_GENRE_ID FOREIGN KEY (Genre_ID)
REFERENCES GENRE (Genre_ID);

desc MOVIE;